### ISSUE TITLE
SUGGESTION: Allow for submission of 2 images instead of 1 for FGO profiles

### ISSUE THREAD

**Issue by fbordas** [aister/nobuBot#6]
By allowing the submission of 2 links or images instead of one for FGO profiles, users would be able to display both their usual day-to-day support setup as well as their event-specific support setup.

**Comment by aister** [comment]
while I do agree with this, the discord's embed don't allow having two images so this is impossible to do. Wat I would suggest is you merge both images together yourselves using Paint or Photoshop or any image editing software, then post it as one big image like u normally would.

With that said, I'll have to close this issue, but if u have any other suggestion don't hesitate to keep on commenting

**Comment by Kibouo** [comment]
A possibility would be to provide a subcommand per support setup. Optionally defaulting to either option when not provided. I.e.: ``$profile [general | event (default=general)]``

**Comment by aister** [comment]
that would create more entries in the database, which I have already tried to limit as much as possible since it runs on free plan.

I have a lot of plan for profiles, but free plans together with having next to no time made it pretty much impossible to do
